lead_length = 109.0
temperature = 300.0
voltage_offsets = [0.0, 0.1]

[[layers]]
thickness = [100.0]
material = "GaAs"
acceptor_density = 0.0
donor_density = 1e24

[[layers]]
thickness = [10.0]
material = "GaAs"
acceptor_density = 0.0
donor_density = 1e18

[[layers]]
thickness = [2.0]
material = "AlGaAs"
acceptor_density = 0.0
donor_density = 1e18

[[layers]]
thickness = [10.0]
material = "GaAs"
acceptor_density = 0.0
donor_density = 1e18

[[layers]]
thickness = [100.0]
material = "GaAs"
acceptor_density = 0.0
donor_density = 1e24
