lead_length = 45.0
temperature = 300.0
voltage_offsets = [0.0, 0.02]

[[layers]]
thickness = [50.0]
material = "GaAs"
acceptor_density = 0.0
donor_density = 1e23

[[layers]]
thickness = [5.0]
material = "GaAs"
acceptor_density = 0.0
donor_density = 1e18

[[layers]]
thickness = [50.0]
material = "GaAs"
acceptor_density = 0.0
donor_density = 1e23
