[package]
name = "transporter-negf"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.6.1"
nalgebra = { version = "0.30.1", features = ["compare"] }
nalgebra-sparse = { version = "0.6.0", features = ["compare", "proptest-support"] }
num-traits = "0.2.14"
serde = { version = "1.0.136", features = ["derive"] }
transporter-mesher = { path = "../transporter-mesher" }

[dev-dependencies]
matrixcompare = { version = "0.3.0", features = ["proptest-support"] }
proptest = "1.0.0"
