[global]
number_of_bands = 1

[inner_loop]
maximum_iterations = 100
tolerance = 1e-5

[outer_loop]
maximum_iterations = 2000
tolerance = 1e-5

[mesh]
unit_size = 1e-9
elements_per_unit = 4
maximum_growth_rate = 1.2

[spectral]
number_of_energy_points = 100
minimum_energy = 0.0
maximum_energy = 0.25
energy_integration_rule = "ThreePoint"
number_of_wavevector_points = 50
maximum_wavevector = 1e9
wavevector_integration_rule = "ThreePoint"

