temperature = 300.0
voltage_offsets = [0.0, 0.0]

[[layers]]
thickness = [20.0]
material = "GaAs"
acceptor_density = 0.0
donor_density = 1e23

[[layers]]
thickness = [10.0]
material = "SiC"
acceptor_density = 0.0
donor_density = 1e23

[[layers]]
thickness = [20.0]
material = "GaAs"
acceptor_density = 0.0
donor_density = 1e23