temperature = 50.0
voltage_offsets = [0.0, 0.0]

[[layers]]
thickness = [2.0]
material = "GaAs"
acceptor_density = 0.0
donor_density = 1e24

[[layers]]
thickness = [1.0]
material = "SiC"
acceptor_density = 0.0
donor_density = 1e24

[[layers]]
thickness = [2.0]
material = "GaAs"
acceptor_density = 0.0
donor_density = 1e24